apiVersion: apps/v1
kind: Deployment
metadata:
  name: 22600-front-counter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 22600-front-counter
  template:
    metadata:
      labels:
        app: 22600-front-counter
    spec:
      hostPID: true
      hostIPC: true
      restartPolicy: Always
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
      - name: 22600-front-counter
        image: ghcr.io/anicca-computer-vision-prod/cv_models_prod:store
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "0"
        - name: CUDA_MPS_PIPE_DIRECTORY
          value: "/run/nvidia/nvidia-mps"
        volumeMounts:
        - mountPath: /run/nvidia
          mountPropagation: HostToContainer
          name: nvidia-mps-path
        - name: config-volume
          mountPath: /
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: nvidia-mps-path
        hostPath:
          path: /run/nvidia/
          type: ""
      - name: config-volume
        configMap:
          name: configmap
