
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service

    spec:
      containers:
      - name: ingestion-service
        image: ghcr.io/anicca-computer-vision/cv-active-metric-db-ingestion:master
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /home/config
          
      volumes:
        - name: config-volume
          configMap:
            name: configmap
            
      imagePullSecrets:
      - name: regcred