apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-model-master-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuda-simple
  template:
    metadata:
      labels:
        app: cuda-simple
    spec:
      hostPID: true
      hostIPC: true
      restartPolicy: Always
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
      - name: cuda-master
        image: ghcr.io/anicca-computer-vision-prod/cv_models_prod:nsn6489
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "0"
        - name: CUDA_MPS_PIPE_DIRECTORY
          value: "/run/nvidia/nvidia-mps"
        volumeMounts:
        - mountPath: /run/nvidia
          mountPropagation: HostToContainer
          name: nvidia-mps-path
      imagePullSecrets:
        - name: regcred
      volumes:
      - hostPath:
          path: /run/nvidia/
          type: ""
        name: nvidia-mps-path
