env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
      - name: Check out my other private repo
        uses: actions/checkout@v3
        with:
          repository: sidharthram98/deployment

      - name: Make changes to gitops pipeline
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import sys
            import yaml
            with open('ingestion-service.yaml') as fp:
              data = yaml.load(fp)
              data["spec"]["template"]["spec"]["containers"][0]["image"] = 'sidharth'
            with open(r'E:\data\store_file.yaml', 'w') as file:
              yaml.dump(data, sys.stdout)

      - name: Git operations
        run: |
          ls 
          cat ingestion-service.yaml
          git config user.name "GitHub Actions Bot"
          git config user.email "sidharth.ram@aniccadata.com"
          git add ingestion-service.yaml && git commit -m "auto deployment enabled.."
          git push origin voe-app
              
      